### ISSUE TITLE
Missing sortBy?

### ISSUE THREAD

**Issue by alensiljak** [simon-kuster/BlazorDexie#10]
Hi!

Based on the docs for OrderBy - https://dexie.org/docs/Table/Table.orderBy() - sorting other fields is done by sorting a collection using .sortBy(). I don't see this method on a collection.
What is the recommended way to do this? Is there any benefit for sorting a Collection vs sorting the resulting list/array?
Cheers

**Comment by simon-kuster** [comment]
Hi

I have added the methods SortBy and SortByToList (same as SortBy but returns a list instead of an array) to the Collection. 

I can't say if it will bring a benefit over sorting the resulting list/array, but the method is available in Dexie and now also in BlazorDexie.

**Comment by alensiljak** [comment]
Thanks a lot! Will try it out today. I'm hoping this can do the sorting before/during loading, instead of after. It is quite different to sort by date and get the first 10 records vs getting the first 10 records and then sorting by date. :)
