### ISSUE TITLE
Need toCollection()

### ISSUE THREAD

**Issue by alensiljak** [simon-kuster/BlazorDexie#11]
Hi! Following up on #10, I upgraded to v1.3.0 to get the new SortBy function. However, there are other underlying changes, which now break the way I did queries.
I used to use .Filter() if there was a search term entered, or just a table (db.Payees), if not. These are no longer compatible.
Hence, I would very much appreciate if the [toCollection()](https://dexie.org/docs/Table/Table.toCollection()) was added. 

This allows to have one object type, on which filtering and sorting are performed before actually fetching the data with .ToList().
Thanks!

**Comment by alensiljak** [comment]
This is not urgent, however. There is a workaround.

**Comment by simon-kuster** [comment]
I see the problem. The return values of many methods had changed from Collection to CollectionBase, which caused this problem. However, I reversed this change with version 1.3.1.

With version 1.4.0 toCollection is added.

**Comment by alensiljak** [comment]
Thanks, man! Where would we be if everyone was as expedient as you are?
