### ISSUE TITLE
Auto Incrementing Primary Key

### ISSUE THREAD

**Issue by scottkuhl** [simon-kuster/BlazorDexie#12]
I am using an auto incrementing integer as the primary key, but I cannot get it to auto increment.  The ID is always zero.  

I have tried defining the first column as both Id and ++Id and the behavior is the same.
https://dexie.org/docs/API-Reference#quick-reference

```
public class AppDb : Db
{
    public Store<Trail, int> Trails { get; set; } = new($"++{nameof(Trail.Id)}", nameof(Trail.Name), nameof(Trail.TimeInMinutes), nameof(Trail.Length));

    public AppDb(IModuleFactory moduleFactory) : base(nameof(ArcaneFX), 1, Array.Empty<DbVersion>(), moduleFactory)
    {

    }
}
```

Blazor Page (form to add record):

```
    private async Task SubmitForm()
    {
        try
        {
            var db = new AppDb(new EsModuleFactory(Js));
            await db.Trails.Add(trail);
        }
...
    }
```

**Comment by simon-kuster** [comment]
To use auto increment, the corresponding property must be nullable. Otherwise it would be initialized with zero and this value will be passed to dexie.js. I don't see your Trail class but I suspect this could be the problem.

Example:
`public int? Id { get; set; }`

**Comment by scottkuhl** [comment]
Thanks for the quick response.  I switched the Id field to nullable and now I get this error when Id is null:

> Error: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path yielded a value that is not a valid key.

If I set the Id manually to the next number just before calling Add it works.

Here is a snapshot of the Trail store:

<img width="426" alt="image" src="https://github.com/simon-kuster/BlazorDexie/assets/4465616/e05bba1f-f6b3-4a10-84ef-bdaa31f48968">


```
public class Trail
{
    public int? Id { get; set; }
    ...
}
```

**Comment by scottkuhl** [comment]
BTW, I would not say this is a show stopper.  I switched the ID to Guid and that worked well.  I also put in a workaround to get the next highest ID using Count() which also works.

There are many Blazor IndexedDB libraries out there and this one is the most up to date and feature rich that I have seen.  Great job!

**Comment by simon-kuster** [comment]
Nice to hear that you are happy with the library.

You are right it doesn't work because the Id property is present in the JavaScript object used internally in the BlazorDexie  and dexie.js either expects the property not to be present or to contain a valid value.
Try to fix it like this (for non nullable):
```
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
public int Id { get; set; }
```

or (for nullable)
```
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
public int Id? { get; set; }
```

**Comment by scottkuhl** [comment]
I think I will stick with Guids anyway, makes it easier to sync up. Thanks for the help.
