### ISSUE TITLE
Transaction always times out, then executes succesfully

### ISSUE THREAD

**Issue by bconte** [simon-kuster/BlazorDexie#14]
Using BlazorDixie 1.5.2 in a .net8 Blazor Web app:

Using the following code:
```
 try {
        await db.Transaction("rw",
        ["TableX", "TableY", "TableZ")],
        20000,
        async () =>
        {
            await db.TableX.BulkDelete(tableXItemsToDelete); 
            await db.TableY.BulkDelete(tableYItemsToDelete);
            await db.TableZ.Delete(tableZItemToDelete);
        });
}
catch (Exception e)
{
   Console.WriteLine(e);
}
```

The transaction always times out on the first line (deleting from TableX), and throws an exception, but the next time the execution yields the anonymous function resumes, executing all 3 deletes succesfully as confirmed by walking through the code with the debugger, and verifying the data no longer existing in the IndexedDb. _(Edit:formatting)_

**Comment by bconte** [comment]
I suspect what is happening is the timeout is releasing the transaction allowing the anonymous function to continue, but the behavior is unexpected, i would expect the anonymous function to terminate or throw as well.

Also not sure why the transaction is causing the deadlock, as there are no other operations ongoing at that time, and none of them use transactions yet, but also not willing to rule out I'm doing something that I don't realize is causing this.

**Comment by simon-kuster** [comment]
I did a test with exactly your code and could not find any problem. What do you mean with "but the next time the execution yields the anonymous function resumes"? What's the next time when there's always a time out? Which browser do you use?
