### ISSUE TITLE
Add PrimaryKeys and Keys per index

### ISSUE THREAD

**Issue by vincentnl** [simon-kuster/BlazorDexie#2]
When storing blobs it is convenient to list the keys only - so to know which blobs are in storage.

I tried to implement by sending the commands 'toCollection' and 'primaryKeys' in succession, but to no avail. My JS is limited.

https://dexie.org/docs/Collection/Collection.primaryKeys()

**Comment by simon-kuster** [comment]
The method Collection.PrimaryKeys was added with the latest version (1.0.0).

Use it like this:

            var youngFriends =  await db.Friends
                .Where("age")
                .Between(0, 25)
                .PrimaryKeys();

**Comment by simon-kuster** [comment]
Close issue
