### ISSUE TITLE
BlazorDexie Version Change 

### ISSUE THREAD

**Issue by rmrudro** [simon-kuster/BlazorDexie#3]
Hello I want to know One thing about Blazor Version Change . ... Can You give us a good tutorial or documentation about Version change . Like Here
        `public IndexedDB(IModuleFactory jsModuleFactory)
            : base("Test", 1, new DbVersion[] { new Version1() }, jsModuleFactory)
        {

        }`   

 You See Here In The IndexDb constructor we Create IndexDB Database and Version 1 ... I can go to Version 3 Without stepping Version 2 .. How can It possible .... Yes From Version 4 Version 1 is Not possible to move ... I need to do this check Not able to go Version 3 without going version 2

**Comment by rmrudro** [comment]
If You do not Understand Please Let me know ... I think My Explanation is not so good

**Comment by simon-kuster** [comment]
Close issue

**Comment by simon-kuster** [comment]
Hi rmrudro

I have add a chapter "Database Versioning" to the readme file. With the version 1.1.0 it is also possible to call Version.upgrade().

Im am not sure if I unterstand your question correct but in your example the class IndexedDB will always define the current version and the previous versions should be pass to the base constructor as a DbVersion array.

Please tell me if the issue is solved with these information.

**Comment by rmrudro** [comment]
Thanks For Adding Database Versioning Chapter It Helps us a lot . But We Did not understand  two things from your note . It will be very helpful if you please explain us . In your Note Database Versioning Version 1  You Wrote 
`   public class MyDb : Db
    {
    public Store<Friend1, int> Friends { get; set; } = new("++" + nameof(Friend.Id), nameof(Friend.Name), nameof(Friend.Age));

    public Db1(IModuleFactory jsModuleFactory)
        : base("TestDb", 1, new DbVersion[0], jsModuleFactory)
    {
    }
     }`  Here  You wrote MyDb Class and and Db1 Method .. But I think This Db1 will be MyDb Constructor .. Or They way you wrote is that new function or not .. I think what I did actually When there is new version then I created Version Like This 
`public class Version1 : DbVersion
{
    public Store<Friend1, int> Friends { get; set; } = new("++id", "name" + "age");

    public Version1() : base(1)
    {
    }
}`  And Inside Version1 class There is a Function name GetUpgrade  What you did inside MyDb Class ...  
The Second thing I want to know that   GetUpgrade   Method Here what you have written 
`  private static string GetUpgrade()
    {
        return
            "var YEAR = 365 * 24 * 60 * 60 * 1000; " +
            "return tx.table(\"Friends\").toCollection().modify(friend => { " +
            "    friend.birthdate = new Date(Date.now() - (friend.age * YEAR)); " +
            "    delete friend.age; " +
            "}); ";
    }`  this function will run be on js write .. Actually I have not understood the purpose of this function .. Is this for trac what we have changed .... if we do like this way do we have to create dbUpgrade2.js .. Thanks in advance

**Comment by simon-kuster** [comment]
Your are right the "method" Db1 in the class MyDb is a constructor and should be named MyDb. The readme is corrected.

The method GetUpgrade returns a string with JavaScript code for the data migration. This code will be run by the dexie method "upgrade". Have a look to https://dexie.org/docs/Version/Version.upgrade() and https://dexie.org/docs/Dexie/Dexie.version() for more information. This upgrade is not always needed, only if you need to change the existing data to be compatible with the new version.

**Comment by rmrudro** [comment]
Thank You For Your Answer I will try to do like this way .. I have another things to know So I am making another issue may be it will also helpful for us develop using BlazorDexie ...

**Comment by rmrudro** [comment]
@simon-kuster  I  have another question regarding IndexDB Versioning .. If there is plural number of table how GetUpgrade Looks Like .For Example If you add two more new table in a new version and changes one table business logic   . As I can See you are returning for example 
`return
"var YEAR = 365 * 24 * 60 * 60 * 1000; " +
"return tx.table("Friends").toCollection().modify(friend => { " +
" friend.birthdate = new Date(Date.now() - (friend.age * YEAR)); " +
" delete friend.age; " +
"}); ";`    Here you are returning string value ... yes i can understand this . But how this code return Dexie/Version.upgrade() could not understand ...As we can see this will return only string not  Dexie.js . Should I have to add any cdn or namespace how can this function return will call upgrade and run this dexie function

**Comment by simon-kuster** [comment]
I am not sure if i understand you right. Do you mean that the C# method return a string? That ist correct but this string contains JavaScript code and this JavaScript code will be executed by on dexie Version.upgrade. If you prefer to write the JavaScript code in separate file as ES6-Module use upgradeModule of BlazorDexie instead.
