### ISSUE TITLE
Joining Store Using BlazorDexie 

### ISSUE THREAD

**Issue by rmrudro** [simon-kuster/BlazorDexie#4]
Hello I want to know How We can  Join using BlazorDexie ... I tried but could not succeed . Now actually I am pulling the 2 store and after  that I join using Linq . But this is not an ideal solution . Can you give us a notes or a way how we can join of two or more store .. Here is My Code   
`
 public class IndexedDB : Db , IDisposable{
public Store <AModel,string> A {get;set;}-new (nameof(A.id));
public Store <AModel,string> B {get;set;}-new (nameof(b.id));

  public IndexedDB(IModuleFactory jsModuleFactory)
            : base("KKK", 2, new DbVersion[] { new Version1() }, jsModuleFactory)
        {

        }

`
And Inside Suppose A Store  Here I am joining two store but since I am not able to use where and joining this two store 
so I am using Linq 

`
var query1 = await _idb.A.ToArray();
            var query2 = await _idb.B.ToArray();
            if(l1Codes!= null)
            {
                var result = (from a in query1
                              join b in query2 on a.l1_code equals b.l1_code
                              where a.flg== "0" && (l1Codes == null || l1Codes.Contains(b.l1_code))

                              select new
                              {
                                  Code = a.id,
                                  Name = a.name
                              }).ToList();

                return result.Select(d => new ListItem
                {
                    key = d.Code,
                    value = d.Name
                }).Distinct().OrderBy(x => x.key).ToList();

`

But this is not an idle solution. will you please teach us that will be very helpful . Thanks

**Comment by simon-kuster** [comment]
Dexie.js doesn't support join and BlazorDexie is only a wrapper around blazor.js, so it does not support join either. I think it is the right way to retrieve the data from each store and combine the results by C# code.
