### ISSUE TITLE
[Feature Request] Add Update(Type object)

### ISSUE THREAD

**Issue by thepra** [simon-kuster/BlazorDexie#5]
I've no need for specific changes to be applied and would rather just push the whole updated object in the Update(...) function, is this something feasible?

**Comment by simon-kuster** [comment]
I have trouble to understand your request. What do you exactly mean with the whole object? With the PUT function it is possible to create or update an object. Do you need transactions? Please tell me which dexie.js function you are missing.

Dexie.js docs: https://dexie.org/docs/

**Comment by thepra** [comment]
My mistake, I've found "PUT" only now. Closing down.
