### ISSUE TITLE
Transaction In IndexDB BlazorDexie

### ISSUE THREAD

**Issue by rmrudro** [simon-kuster/BlazorDexie#6]
Hello, Will you please teach  us how to implement Transaction In BlazorDexie . Do we have to use raw  JavaScript I mean Raw Dexie.js or can we use Wrapper as  BlazorDexie ... Please teach us as we need Rollback functionality on IndexDB so we have to use Transaction

**Comment by simon-kuster** [comment]
At the moment transactions are not supported with BlazorDexie. We will check if and how we can add support.

**Comment by simon-kuster** [comment]
Transactions are supported now with version 1.5.0.
