### ISSUE TITLE
Breaking change - somewhat unclear - userModulePathBase

### ISSUE THREAD

**Issue by vincentnl** [simon-kuster/BlazorDexie#8]
The new EsModuleFactory has a new required parameter.
It was added in the commit for increased testability.

The documentation shows the class with the old constructor.

What is required here? Can we add String.Empty?

```
public EsModuleFactory(IJSRuntime jsRuntime, string userModulePathBase)
        {
            _jsRuntime = jsRuntime;
            _userModulePathBase = userModulePathBase;
        }
```

**Comment by simon-kuster** [comment]
That is a mistake, the parameter userModulePathBase should be optional. 
With the version 1.1.4 this is fixed. With an empty string it would also work.
