### ISSUE TITLE
Error inserting a record

### ISSUE THREAD

**Issue by alensiljak** [simon-kuster/BlazorDexie#9]
Hi! I'm trying to figure out what is causing the exception in this case.

The entity I'm trying to save is defined as:
```
    public class Xact()
    {
        public long? Id { get; set; }
        public DateTime Date { get; set; }
        public string? Payee { get; set; }
        public string? Note { get; set; }
        public List<Posting>? Postings { get; set; }
    }
```

The store is defined as
```
public Store<Xact, string> Xacts { get; set; } = new("++" + nameof(Xact.Id), nameof(Xact.Date));
```

When trying to save via Put (the same with Add, though), an exception is thrown.

The error is:
```
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 18.. See InnerException for more details.
```

The problem, however, is not with saving since the records indeed do get inserted into the store. I believe the problem is in the Put method
```
var result = await _db.Xacts.Put(xact);
```
which is trying to return a numeric Id as a string.

**Comment by alensiljak** [comment]
As usual, only after listing all the items like this, does the problem become obvious. Cheers!

**Comment by ondeveloper** [comment]
Hi @alensiljak 
Been a long time but may I ask what became obvious since I'm getting the same error.

**Comment by alensiljak** [comment]
> Hi [@alensiljak](https://github.com/alensiljak) Been a long time but may I ask what became obvious since I'm getting the same error.

Ouch! That's hard to remember now. But it must be something simple and mentioned in the issue report.
If it can help you, my codebase is here: https://github.com/alensiljak/cashier-blazor
Perhaps you can compare to your case and see where the issue comes from? It is likely the type of the Id or something rather simple.

**Comment by ondeveloper** [comment]
Thanks will check that!

**Comment by simon-kuster** [comment]
Hi @ondeveloper 

The second generic parameter, TKey, of the Store should be the type of the Id. 

In your case:
`public Store<Xact, long> Xacts { get; set; } = new("++" + nameof(Xact.Id), nameof(Xact.Date));`

**Comment by ondeveloper** [comment]
Thanks @simon-kuster and @alensiljak !
